name: Setup
description: Setup environment and cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 20.9.0
        cache: pnpm
    - run: pnpm install
      shell: bash
    - run: pnpm add --global turbo
      shell: bash
