name: setup
description: setup dependencies and cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: '6.32.2'
    - uses: actions/setup-node@v2
      with:
        node-version: '16.14.x'
        cache: 'pnpm'
    - run: pnpm install
      shell: bash
    - uses: actions/cache@v2
      with:
        path: ./node_modules/.cache/turbo
        key: turbo-${{ github.job }}-${{ github.ref }}
