services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  trpc:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./apps/trpc/docker/Dockerfile
    restart: always
    env_file: ./apps/trpc/.env
    ports:
      - 5173:5173

volumes:
  db:
